#!/usr/bin/env python
import os
env = Environment()
env['HOME'] = os.environ['HOME']

#WRAPLIB = '${HOME}/.local/lib/python2.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so'
#FWLIB = '${HOME}/.local/lib/python2.7/site-packages/tensorflow_core/libtensorflow_framework.so.2'

env.Program('kriging',['test_kriging.c','lib/ontheflysurrogate.c']
	,CFLAGS = ['-g']
	,LIBS =['m','gsl','gslcblas','python2.7','tensorflow']
)

