#! /bin/env python

import argparse

from solartherm import postproc
from solartherm import plotting

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument('file',
			help='result mat-file to read')
	parser.add_argument('-n', '--names', action='store_true',
			help='print out variable names and exit')
	parser.add_argument('-o', '--outfile',  nargs=1, type=str, default=[None],
			help='save figure to outfile instead of displaying')
	parser.add_argument('--xlim', nargs=2, type=float,
			help='domain of x axis')
	parser.add_argument('var', metavar='V', type=str, nargs='*',
			help='v1,v2:v3 v4:v5 ...')
	args = parser.parse_args()

	fn = args.file
	res = postproc.SimResult(fn)
	if args.names:
		print(sorted(str(n) for n in res.mat.names()))
	else:
		plotting.plot_res(res, args.var, xlim=args.xlim, out=args.outfile[0])

# example call:
# st_plotmat EnergySystem_res.mat 'tnk.E:der(tnk.E)' 'pmp.frac'
