#! /bin/env python
import argparse
import os
import itertools
from multiprocessing import Pool
from functools import partial
from solartherm import postproc
from solartherm import simulation

# TODO: Pass on any command line arguments to simulation executable
# TODO: Save separate results files
# TODO: Pull together relevant results

def simulation_worker(fn, start, stop, step, args, par_n, suff, val):
	sim = simulation.Simulator(fn, suffix=suff);
	sim.load_init()
	sim.update_pars(par_n, val)
	sim.simulate(start=start, stop=stop, step=step, args=args)
	res = postproc.SimResult(sim.res_fn)
	perf = res.calc_perf()
	return perf

class LoggerPerf(object):
	perf_names = [n + ' (' + u + ')' for n, u in
			zip(postproc.SimResult.perf_n, postproc.SimResult.perf_u)]
	@classmethod
	def header(cls):
		print('Starting simulation')
		print(','.join(['index']+cls.perf_names))
	@classmethod
	def entry(cls, suff, perf):
		print(','.join([suff]+list(str(perf[j])
			for j, n in enumerate(cls.perf_names))))

def simulation_callback(perfs, i, perf):
	perfs[i] = perf
	LoggerPerf.entry(str(i), perf)

if __name__ == '__main__':
	"""
	Should make sure parameters are not final (protected), or that other
	derived parameters are final.
	For example, the internal starting level and height of an OpenTank is final
	"""
	parser = argparse.ArgumentParser()
	parser.add_argument('file',
			help='model file name')
	parser.add_argument('-v', action='store_true',
			help='verbose')
	parser.add_argument('--nomc', action='store_true',
			help='no model compilation')
	parser.add_argument('--nosc', action='store_true',
			help='no simulation compilation')
	parser.add_argument('--noc', action='store_true',
			help='no compilation at all (--nomc and --nosc)')
	parser.add_argument('--nosim', action='store_true',
			help='no simulation')
	parser.add_argument('--start', type=str, default='0',
			help='simulation start time: <number>[,y,d,m,s]')
	parser.add_argument('--stop', type=str, default='1y',
			help='simulation stop time: <number>[,y,d,m,s]')
	parser.add_argument('--step', type=str, default='5m',
			help='simulation time step: <number>[,y,d,m,s]')
	parser.add_argument('--plot', type=str, default=None,
			help='plot given quantity (at most 2 parameter dimensions)')
	parser.add_argument('--plot3d', action='store_true',
			help='plot in 3d')
	#parser.add_argument('--mcargs', nargs=1, type=str, default=[],
	#		help='model compilation arguments')
	parser.add_argument('--sargs', type=str, default=None,
			help='simulation arguments')
	parser.add_argument('--nth', type=int, default=None,
			help='number of threads')
	#parser.add_argument('--nthsim', type=int, default=None,
	#		help='number of threads per simulation')
	parser.add_argument('par', metavar='P', type=str, nargs='*',
			help='set or sweep parameters, e.g.: p1=val1,val2 p2=val3')
	args = parser.parse_args()

	sim = simulation.Simulator(args.file);

	mcargs = []
	#if len(args.mcargs) == 1:
	#	mcargs = args.mcargs[0].split(' ')

	sargs = []
	if args.sargs is not None:
		sargs = args.sargs[0].split(' ')

	if not args.noc:
		if not args.nomc:
			print('Compiling model')
			sim.compile_model(args=mcargs)
		if not args.nosc:
			print('Compiling simulator')
			sim.compile_sim(args=([] if args.v else ['-s']))

	sim.load_init()

	dims = [] # dimensions
	par_n = [] # names
	par_v = [] # values
	for pp in args.par:
		k, v = pp.split('=')
		par_n.append(k)
		vals = [str(simulation.parse_var_val(vv, sim.get_unit(k)))
			for vv in v.split(',')]
		par_v.append(vals)

		if len(vals) >= 2:
			dims.append(len(par_n) - 1)

	f_ilog = open(sim.model+'_init.log', 'w')
	f_ilog.write(','.join(['index']+par_n) + '\n')
	var_vals = []
	for i, val in enumerate(itertools.product(*par_v)):
		var_vals.append(val)
		f_ilog.write(','.join([str(i)]+list(val)) + '\n')

	perfs = [None]*len(var_vals)
	if not args.nosim:
		LoggerPerf.header()
		worker_enc = partial(simulation_worker, args.file, args.start,
				args.stop, args.step, sargs, par_n)
		pool = Pool(processes=args.nth)
		# using apply instead of map because have more than 1 arg to pass
		for i, val in enumerate(var_vals):
			pool.apply_async(worker_enc, args=(str(i), val),
					callback=partial(simulation_callback, perfs, i))
		pool.close()
		pool.join()
		#for i, val in enumerate(var_vals):
		#	perf = worker_enc(str(i), sval)
		#	print(','.join([str(i)]+list(str(perf[j])
		#		for j, n in enumerate(perf_names))))
		#	perfs.append(perf)

	if args.plot is not None:
		from solartherm import plotting
		ys = []
		ylabels = []
		for name in args.plot.split(','):
			try:
				pei = postproc.SimResult.perf_n.index(name)
			except ValueError:
				raise ValueError('Value to plot should be one of '
						+ str(postproc.SimResult.perf_n))
			ys.append([p[pei] for p in perfs])
			ylabels.append(name + ' (' + postproc.SimResult.perf_u[pei] + ')')
		if len(dims) == 1:
			x1 = [v[dims[0]] for v in var_vals]
			xlabel = par_n[dims[0]] + ' (' + sim.get_unit(par_n[dims[0]]) + ')'
			plotting.plot_par1(x1, ys, xlabel=xlabel, ylabels=ylabels)
		elif len(dims) == 2 and not args.plot3d:
			x1 = [v[dims[0]] for v in var_vals]
			x2 = [v[dims[1]] for v in var_vals]
			x1label = par_n[dims[0]] + ' (' + sim.get_unit(par_n[dims[0]]) + ')'
			x2label = par_n[dims[1]] + ' (' + sim.get_unit(par_n[dims[1]]) + ')'
			plotting.plot_par2(x1, x2, ys, x1label=x1label, x2label=x2label,
					ylabels=ylabels)
		elif len(dims) == 2 and args.plot3d:
			x1 = [float(v[dims[0]]) for v in var_vals]
			x2 = [float(v[dims[1]]) for v in var_vals]
			x1label = par_n[dims[0]] + ' (' + sim.get_unit(par_n[dims[0]]) + ')'
			x2label = par_n[dims[1]] + ' (' + sim.get_unit(par_n[dims[1]]) + ')'
			plotting.plot_3d(x1, x2, ys[0], xlabel=x1label, ylabel=x2label,
					zlabel=ylabels[0])
		else:
			print('Cannot plot problem with ' + str(len(dims)) + ' dimensions')

