#! /bin/env python

import argparse
import os

def load_file(fn):
	return 0

def save_file(dat, fn):
	f = open(fn, 'w')
	f.write('outputting')

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument('file')
	args = parser.parse_args()

	fn = args.file
	dat = load_file(fn)
	save_file(dat, os.path.splitext(fn)[0] + '.mo')
