language: python
# Note that should use pip for all python libraries not apt-get
# We can install the system scipy and matplotlib because we only target 2.7
# (the system default)
python:
  - "2.7"
sudo: required
dist: precise
#dist: trusty
virtualenv:
  system_site_packages: true
before_install:
  - for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` stable"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
  - wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y openmodelica unionfs-fuse
  - sudo apt-get install -qq -y python-scipy python-matplotlib
  - pip2 install dymat pyswarm cma
install:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -DMODELICA_LIBRARY_INSTALL_DIR=$HOME/.openmodelica/libraries/
  - make
  - make install
  - export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$VIRTUAL_ENV/lib:$LIBRARY_PATH"
script:
  - ctest -V
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08b1c444d5db05a9d806
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
