Import('env')
import sys

setuppy = env.Substfile('setup.py.in')

initpy = env.Substfile('solartherm/__init__.py.in')


pipwheel = env.Command('mytouch','setup.py',[
		Delete('wheel')
		,Mkdir('wheel')
		,'%s -m pip wheel --wheel-dir=wheel .' % (sys.executable,)
		,'touch ../mytouch'
	],chdir=True
)
env.Depends(pipwheel,initpy)

wheel = env.Glob('wheel/*.whl')

env.Depends(wheel,pipwheel)

pipinst = env.Command(
	target = '$PREFIX/lib/python$PYVERSION/site-packages/solartherm/__init__.py'
	,source = wheel
	,action = ['%s -m pip install --prefix=$PREFIX --upgrade $SOURCE'%(sys.executable,)]
)

# vim: ts=4:sw=4:noet:tw=80
