name: DAKOTA Linux

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    env:
      DAKVER: 6.14.0
      DAKOTA_PKGN: dakota-6.14.0-${{ matrix.os }}-x86_64-jp
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install gcc g++ gfortran cmake libboost-all-dev libblas-dev liblapack-dev libopenmpi-dev openmpi-bin gsl-bin libgsl-dev python perl libhdf5-dev

    - name: Download DAKOTA
      run: |
        wget https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-$DAKVER-release-public-src-cli.tar.gz
        tar zxf dakota-$DAKVER-release-public-src-cli.tar.gz
        ls -l
        cd dakota-${DAKVER}.src
        
    - name: Build DAKOTA
      run: |
        cd dakota-${DAKVER}.src
        mkdir build && cd build
        cmake -DCMAKE_C_FLAGS="-O2" -DCMAKE_CXX_FLAGS="-O2" -DCMAKE_Fortran_FLAGS="-O2" -DDAKOTA_HAVE_GSL:BOOL=TRUE -DHAVE_QUESO:BOOL=TRUE -DDAKOTA_HAVE_MPI:BOOL=TRUE -DDAKOTA_HDF5:BOOL=TRUE -DBoost_NO_BOOST_CMAKE:BOOL=TRUE ..
        make
        
    - name: Install DAKOTA
      run: |
        cd dakota-${DAKVER}.src/build
        make DESTDIR=$HOME/$DAKOTA_PKGN install
        cd $HOME
        tar zcf ${DAKOTA_PKGN}.tar.gz $DAKOTA_PKGN/*

    - name: Upload DAKOTA binary
      uses: actions/upload-artifact@v2
      with:
        name: $DAKOTA_PKGN
        path: $HOME/${DAKOTA_PKGN}.tar.gz

# vim: ts=2:sw=2:et
