name: DAKOTA Linux

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    env:
      DAKVER: 6.14.0

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install gcc g++ gfortran cmake libboost-all-dev libblas-dev liblapack-dev libopenmpi-dev openmpi-bin gsl-bin libgsl-dev python perl libhdf5-dev

    - name: Download DAKOTA
      run: |
        export DAKFILE=dakota-$DAKVER-release-public-src-cli.tar.gz
        wget --no-verbose https://dakota.sandia.gov/sites/default/files/distributions/public/$DAKFILE
        tar zxf $DAKFILE

    - name: Build DAKOTA
      run: |
        cd dakota-$DAKVER.src
        mkdir build 
        cmake -DCMAKE_C_FLAGS="-O2" -DCMAKE_CXX_FLAGS="-O2" -DCMAKE_Fortran_FLAGS="-O2" -DDAKOTA_HAVE_GSL:BOOL=TRUE -DHAVE_QUESO:BOOL=TRUE -DDAKOTA_HAVE_MPI:BOOL=TRUE -DDAKOTA_HDF5:BOOL=TRUE -DBoost_NO_BOOST_CMAKE:BOOL=TRUE build 
        cd build
        make

    - name: Tar DAKOTA
      run: |
        export DAKPKG=dakota-$DAKVER-linux-x86_64-jp
        cd dakota-$DAKVER.src/build
        make DESTDIR=$HOME/$DAKPKG install
        cd $HOME
        tar zcf $DAKPKG.tar.gz $DAKPKG/*

    - name: Upload DAKOTA binary
      uses: actions/upload-artifact@v2
      with:
        name: dakota-${{ env.DAKVER }}-linux-x86_64-jp
        path: $HOME/dakota-${{ env.DAKVER }}-linux-x86_64-jp.tar.gz

