# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SolarTherm Linux

on:
  workflow_dispatch:
    #
  push:
    branches: [ $default-branch, master-m ]
  pull_request:
    branches:  [ $default-branch, master-m ]
    #[ $default-branch, master-m ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8] 
        #[3.7, 3.8, 3.9]

    env:
      DAKVER: 6.14.0

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo python -m pip install scons flake8 scipy matplotlib DyMat pyswarm cma deap scoop nose solsticepy
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/python --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/python --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install OpenModelica
      run: |
        for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
        wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
        sudo apt update
        sudo apt install build-essential openmodelica omlib-modelica-3.2.3 libglpk-dev

    - name: Install Solstice
      run: |
        wget https://www.meso-star.com/projects/solstice/downloads/Solstice-0.9.0-GNU-Linux64.tar.gz
        tar zxf Solstice-0.9.0-GNU-Linux64.tar.gz
        mkdir -p ~/.local
        cp -R Solstice-0.9.0-GNU-Linux64/* ~/.local
        
#    - name: Download DAKOTA
#      uses: actions/download-artifact@v2
#      with:
#        name: dakota-${{ env.DAKVER }}-linux-x86_64-jp
#
#    - name: Install DAKOTA
#      run: |
#        export DAKPKG=dakota-$DAKVER-linux-x86_64-jp
#        unzip $DAKPKG.zip
#        tar zxf $DAKPKG.tar.gz
#        sudo cp -R $DAKPKG/usr/local/* /usr/local

    - name: Build SolarTherm
      run: |
        scons

    - name: Install SolarTherm
      run: |
        scons install

    - name: Run SolarTherm tests
      run: |
        export PATH=~/.local/bin:$PATH
        export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
        echo "-------DYMAT-----"
        python3 -c "import DyMat; print(DyMat.__version__)"
        echo "-------st env-----"
        st env
        env
        echo "-------DYMAT-----"
        python3 -c "import DyMat; print(DyMat.__version__)"
        echo "-------testing...-----"
        cd tests
        python TestXMLParameter_st_simulate.py
        #nosetests
        
# vim: ts=2:sw=2:et
