# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SolarTherm MSYS2

on:
  workflow_dispatch:
    branches: [ $default-branch, master-m ]
  push:
    branches: [ $default-branch, master-m ]
  pull_request:
    branches:  [ $default-branch, master-m ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: msys2 {0}

    env:
      PY_FORCE_COLOR: 1

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git svn wget zip unzip tar make diffutils patch 
          autoconf automake m4 pkg-config libtool bison 
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-opencl-headers
          mingw-w64-x86_64-openblas
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-wheel
          mingw-w64-x86_64-python-pyzmq
          mingw-w64-x86_64-python-numpy
          mingw-w64-x86_64-python-scipy
          mingw-w64-x86_64-python-matplotlib
          mingw-w64-x86_64-python-pytest
          mingw-w64-x86_64-glpk
    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        echo "WHICH PYTHON =" `which python`
        python -m pip install scons DyMat pyswarm cma deap scoop

    - name: Install OpenModelica
      run: |
        mkdir -p ~/.local
        tar zxv -C ~/.local < <(wget "https://cloudstor.aarnet.edu.au/plus/s/BktvwWvCdgboDY6/download" -q -O-)

    - name: Build SolarTherm
      run: |
        export PATH=$PATH:~/.local/bin
        scons

    - name: Install SolarTherm
      run: |
        export PATH=$PATH:~/.local/bin
        scons install

    - name: Run SolarTherm tests 1
      run: |
        echo "--------------setting path----------"
        export PATH=$PATH:~/.local/bin
        cd tests
        st python -m pytest test_python_env.py test_stenv.py test_solstice.py

#    - name: Run SolarTherm tests 2
#      run: |
#        echo "--------------setting path----------"
#        export PATH=$PATH:~/.local/bin
#        echo "--------------starting st env shell----------"
#        VERBOSE=1 st env
#        echo "--------------cd tests----------"
#        cd tests
#        echo "--------------python TestCatromOE.py----------"
#        python TestCatromOE.py
        
# vim: ts=2:sw=2:et
