# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SolarTherm MSYS2

on:
  workflow_dispatch:
    branches: [ $default-branch, master-m ]
  push:
    branches: [ $default-branch, master-m ]
  pull_request:
    branches:  [ $default-branch, master-m ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: msys2 {0}

    env:
      PYTEST_ADDOPTS: --color=yes
      DAKVER: 6.14.0

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git svn wget zip unzip tar make diffutils patch 
          autoconf automake m4 pkg-config libtool bison 
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-opencl-headers
          mingw-w64-x86_64-openblas
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-wheel
          mingw-w64-x86_64-python-pyzmq
          mingw-w64-x86_64-python-numpy
          mingw-w64-x86_64-python-scipy
          mingw-w64-x86_64-python-matplotlib
          mingw-w64-x86_64-glpk
    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        echo "WHICH PYTHON =" `which python`
        python3 -m pip install scons DyMat pyswarm cma deap scoop solsticepy openpyxl colorama pytest

    - name: Install OpenModelica
      run: |
        mkdir -p ~/.local
        tar zxv -C ~/.local < <(wget "https://cloudstor.aarnet.edu.au/plus/s/BktvwWvCdgboDY6/download" -q -O-)

    - name: Install Solstice
      run: |
        wget https://github.com/anustg/solstice-scripts/releases/download/v0.9.0-3/solstice-0.9.0.exe
        cmd /C "start solstice-0.9.0.exe /S"
        python3 -c "import solsticepy;print(solsticepy.find_prog('solstice'))"

    - name: Install MPIEXEC
      run: |
        wget "https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe"
        cmd /C "start msmpisetup.exe -unattend -force"
        
    - name: Install DAKOTA
      run: |
        export DAKPLAT=Windows.x64
        export PKGN=dakota-${DAKVER}-release-public-${DAKPLAT}-cli
        export DIRN=dakota-${DAKVER}.${DAKPLAT}
        cd
        mkdir -p dakota-tmp
        wget "https://dakota.sandia.gov/sites/default/files/distributions/public/${PKGN}.zip"
        cd dakota-tmp
        unzip ~/$PKGN
        cp -R $DIRN/* ~/.local/
        export PATH=$PATH:~/.local/bin
        dakota --version

    - name: Build SolarTherm
      run: |
        export PATH=$PATH:~/.local/bin
        scons

    - name: Install SolarTherm
      run: |
        export PATH=$PATH:~/.local/bin
        scons install

    - name: Test SolarTherm st env
      run: |
        export PATH=$PATH:~/.local/bin
        export PATH="$PATH:/c/Program\ Files/Microsoft\ MPI/Bin"
        echo $PATH
        mpiexec
        cd tests
        python3 -m pytest test_stenv.py

#    - name: Test SolarTherm dakota
#      run: |
#        export PATH=$PATH:~/.local/bin
#        export PATH="$PATH:/c/Program Files/Microsoft MPI/Bin"
#        echo "WHICH ST? [" `which st` "]"
#        cd tests
#        st python -m pytest test_stopt.py

    - name: Test SolarTherm
      run: |
        export PATH=$PATH:~/.local/bin
        export PATH="$PATH:/c/Program Files/Microsoft MPI/Bin"
        mpiexec
        cd tests
        st python -m pytest

# vim: ts=2:sw=2:et
